### ISSUE TITLE
doesnt work for me

### ISSUE THREAD

**Issue by olszak94** [pinceladasdaweb/Progress#2]
i dont know why, but it doesnt work for me, here's website im trying to use it on http://craftbest.com.pl/forum2/index.php

**Comment by pinceladasdaweb** [comment]
@olszak94 

Call the Javascript function before body tag it will work correctly.

Example:

```
    <!-- Loading and initialize the progress lib -->
    <script src="/path/to/progress.min.js"></script>
    <script>Progress.init();</script>
</body>
```

</html>
